version: "3.7"

services:
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER
    ports:
      - 5432:5432
    command: postgres -c log_statement=all
  mysql:
    image: mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    volumes:
      - ./.docker/mysql/conf:/etc/mysql/conf.d
      - ./volumes/mysql/dump:/docker-entrypoint-initdb.d
      - ./volumes/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped
    environment:
      - TZ
      - MYSQL_HOST
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
  nextcloud:
    build:
      context: .docker/app
      args:
        version_php: ${VERSION_PHP}
        version_xdebug: ${VERSION_XDEBUG}
        version_node: ${VERSION_NODE}
        host_uid: ${UID}
        host_gid: ${GID}
    volumes:
      - ./.docker/app/wait-for-db.php:/var/www/scripts/wait-for-db.php
      - ./.env:/var/www/.env
      - ~/.composer:/root/.composer/
      - ~/.npm:/root/.npm/
      - ./volumes/cfssl:/cfssl
      - ./volumes/nextcloud:/var/www/html
    restart: unless-stopped
    environment:
      - DEFAULT_PHONE_REGION
      - NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - MYSQL_HOST
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - VERSION_NEXTCLOUD
      - AUTOINSTALL
      - XDEBUG_CONFIG
  nginx:
    build: .docker/web
    restart: unless-stopped
    volumes:
      - ./volumes/nextcloud:/var/www/html:ro
      - ./volumes/nginx/includes:/etc/nginx/conf.d/includes/
    ports:
      - ${HTTP_PORT}:80
  mailhog:
    image: blueimp/mailhog
    ports:
      - ${MAILHOG_PORT}:8025
  redis:
    image: redis
