version: "3.7"

services:
  db:
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - .docker/volumes/postgres/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
    command: postgres -c log_statement=all
  app:
    build: .docker/app
    links:
      - db
    volumes:
      - ./:/var/www
    restart: unless-stopped
    ports:
      - $HTTP_PORT:$HTTP_PORT
    env_file:
      - .env
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1"
  mailhog:
    image: blueimp/mailhog
    ports:
      - 8025:8025
