version: "3.7"

services:
  db:
    image: postgres:12-alpine
    restart: always
    volumes:
      - .docker/volumes/postgres/data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
  app:
    build: .docker/app
    links:
      - db
    volumes:
      - ./:/var/www
    restart: always
    ports:
      - $HTTP_PORT:$HTTP_PORT
    env_file:
      - .env
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1"