version: "3.7"

services:
  postgres:
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER
    ports:
      - 5432:5432
    command: postgres -c log_statement=all
  nextcloud:
    build:
      context: .docker/app
      args:
        version_php: ${VERSION_PHP}
        version_xdebug: ${VERSION_XDEBUG}
        version_node: ${VERSION_NODE}
        version_jsignpdf: ${VERSION_JSIGNPDF}
    links:
      - postgres
    volumes:
      - ./.docker/app/wait-for-db.php:/var/www/scripts/wait-for-db.php
      - ./.env:/var/www/.env
      - ~/.composer:/root/.composer/
      - ~/.npm:/root/.npm/
      - ./volumes/cfssl:/cfssl
      - ./volumes/nextcloud:/var/www/html
    restart: unless-stopped
    ports:
      # libresign documentations
      - ${LIBRESIGN_DOCUMENTATION_PORT}:8080
    environment:
      - NEXTCLOUD_VERSION
      - NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - XDEBUG_CONFIG
  nginx:
    build: .docker/web
    restart: unless-stopped
    volumes:
      - ./volumes/nextcloud:/var/www/html:ro
    depends_on:
      - nextcloud
    ports:
      - ${HTTP_PORT}:80
  mailhog:
    image: blueimp/mailhog
    ports:
      - ${MAILHOG_PORT}:8025
  cfssl:
    image: cfssl/cfssl
    volumes:
      - ./volumes/cfssl:/cfssl
    working_dir: /cfssl
    entrypoint: /bin/bash
    ports:
      - 8888:8888
    command:
      - /cfssl/entrypoint.sh
