services:
  pgsql:
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - ./volumes/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-nextcloud}
      - POSTGRES_USER=${POSTGRES_USER:-nextcloud}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-nextcloud}
    ports:
      - 127.0.0.1:5432:5432
    command: postgres -c log_statement=all
  mysql:
    image: mysql
    cap_add:
      - SYS_NICE  # CAP_SYS_NICE
    volumes:
      - ./.docker/mysql/conf:/etc/mysql/conf.d
      - ./volumes/mysql/dump:/docker-entrypoint-initdb.d
      - ./volumes/mysql/data:/var/lib/mysql
    ports:
      - 127.0.0.1:3306:3306
    restart: unless-stopped
    environment:
      - TZ
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-root}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-nextcloud}
  nextcloud:
    image: ghcr.io/librecodecoop/nextcloud-dev-php${PHP_VERSION:-80}:latest
    volumes:
      - ./.docker/scripts/wait-for-db.php:/var/www/scripts/wait-for-db.php
      - ./.env:/var/www/.env
      - ~/.composer:/root/.composer/
      - ~/.npm:/root/.npm/
      - ./volumes/nextcloud:/var/www/html
    restart: unless-stopped
    environment:
      - DEFAULT_PHONE_REGION
      - NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD
      - DB_HOST=${DB_HOST:-mysql}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nextcloud}
      - MYSQL_USER=${MYSQL_USER:-nextcloud}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-nextcloud}
      - POSTGRES_DB=${POSTGRES_DB:-nextcloud}
      - POSTGRES_USER=${POSTGRES_USER:-nextcloud}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-nextcloud}
      - VERSION_NEXTCLOUD
      - AUTOINSTALL
      - XDEBUG_CONFIG
  nginx:
    build: .docker/web
    restart: unless-stopped
    volumes:
      - ./volumes/nextcloud:/var/www/html:ro
      - ./volumes/nginx/includes:/etc/nginx/conf.d/includes/
    ports:
      - 127.0.0.1:${HTTP_PORT}:80
  mailhog:
    image: blueimp/mailhog
    ports:
      - 127.0.0.1:${MAILHOG_PORT}:8025
  redis:
    image: redis
