server {
    listen 443 ssl;
    http2 on;
    large_client_header_buffers 4 16k;

    ssl_certificate /certs/nextcloud.pem;
    ssl_certificate_key /certs/nextcloud.pem;
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    include /etc/nginx/conf.d/includes/*.conf;

    include /etc/nginx/conf.d/common.conf;
}


