services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.11.6-alpine@sha256:99376e95c8754547213d411222a2c4dca046d974e753ae2a1c9aef09b2c03364
    container_name: librecode-dev-proxy
    labels:
      coop.librecode.dev-proxy: "true"
    working_dir: /dashboard
    command: ["forego", "start", "-r"]
    ports:
      - "${IP_BIND:-127.0.0.1}:80:80"
      - "${IP_BIND:-127.0.0.1}:443:443"
    volumes:
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:/tmp/docker.sock:ro
      - librecode-dev-proxy-vhost:/etc/nginx/vhost.d
      - librecode-dev-proxy-assets:/dashboard:ro
      - librecode-dev-proxy-log:/etc/nginx/log
      - librecode-dev-proxy-certs:/etc/nginx/certs:ro
    environment:
      - ENABLE_IPV6=true
      - VIRTUAL_HOST=localhost,*.localhost
      - VIRTUAL_PORT=80
      - SELF_SIGNED_HOST=localhost,*.localhost
    networks:
      - proxy

  ssl-companion:
    image: sebastienheyd/self-signed-proxy-companion:1.1.0@sha256:dd698341f804aaffe2974931a185aa088561d76094e040e374847f3a64004d43
    container_name: librecode-dev-proxy-ssl-companion
    labels:
      coop.librecode.dev-proxy-companion: "true"
    volumes:
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock:ro
      - librecode-dev-proxy-certs:/etc/nginx/certs:rw
    environment:
      - NGINX_PROXY_CONTAINER=librecode-dev-proxy
    networks:
      - proxy

networks:
  proxy:
    name: librecode-dev-proxy
    external: true

volumes:
  librecode-dev-proxy-vhost:
    name: librecode-dev-proxy-vhost
  librecode-dev-proxy-assets:
    name: librecode-dev-proxy-assets
  librecode-dev-proxy-log:
    name: librecode-dev-proxy-log
  librecode-dev-proxy-certs:
    name: librecode-dev-proxy-certs
