services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.11.6-alpine
    container_name: librecode-dev-proxy
    labels:
      coop.librecode.dev-proxy: "true"
    working_dir: /dashboard
    command: ["forego", "start", "-r"]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:/tmp/docker.sock:ro
      - librecode-dev-proxy-vhost:/etc/nginx/vhost.d
      - librecode-dev-proxy-assets:/dashboard:ro
      - librecode-dev-proxy-log:/etc/nginx/log
      - librecode-dev-proxy-certs:/etc/nginx/certs:ro
    environment:
      - ENABLE_IPV6=true
      - VIRTUAL_HOST=localhost,*.localhost
      - VIRTUAL_PORT=80
      - SELF_SIGNED_HOST=localhost,*.localhost
    networks:
      - proxy

  ssl-companion:
    image: sebastienheyd/self-signed-proxy-companion:1.1.0
    container_name: librecode-dev-proxy-ssl-companion
    labels:
      coop.librecode.dev-proxy-companion: "true"
    volumes:
      - ${DOCKER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock:ro
      - librecode-dev-proxy-certs:/etc/nginx/certs:rw
    environment:
      - NGINX_PROXY_CONTAINER=librecode-dev-proxy
    networks:
      - proxy

networks:
  proxy:
    name: librecode-dev-proxy
    external: true

volumes:
  librecode-dev-proxy-vhost:
    name: librecode-dev-proxy-vhost
  librecode-dev-proxy-assets:
    name: librecode-dev-proxy-assets
  librecode-dev-proxy-log:
    name: librecode-dev-proxy-log
  librecode-dev-proxy-certs:
    name: librecode-dev-proxy-certs
