on:
  pull_request:
  push:
    branches:
      - main

name: 'Shellcheck'

permissions:
  contents: read

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0
      env:
        SHELLCHECK_OPTS: -x
      with:
        version: v0.11.0
        scandir: .docker/
        check_together: 'true'
